# Project: SK8
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o nbtrees.o
LINKOBJ  = main.o nbtrees.o
LIBS     = -L"E:/DevCpp/Dev-Cpp/TDM-GCC-64/lib" -L"E:/DevCpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/DevCpp/Dev-Cpp/TDM-GCC-64/include" -I"E:/DevCpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/DevCpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"E:/DevCpp/Dev-Cpp/TDM-GCC-64/include" -I"E:/DevCpp/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/DevCpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/DevCpp/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = SK8.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = E:\DevCpp\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

nbtrees.o: nbtrees.c
	$(CC) -c nbtrees.c -o nbtrees.o $(CFLAGS)
